<?php

/*******************************************************************************
 * Hook Functions (Ubercart)
 ******************************************************************************/

function uc_sermepa_gateway_payment_gateway() {
  
  $gateways[] = array(
    'id' => 'uc_sermepa_gateway',
    'title' => t('Sermepa Gateway'),
    'description' => t('Process credit card payments through Sermepa Gateway.'),
		'settings' => 'uc_sermepa_gateway_admin_settings',
    'credit' => 'uc_sermepa_gateway_charge',
    'credit_txn_types' => array(UC_CREDIT_AUTH_CAPTURE),
  );

  return $gateways;
}

/*******************************************************************************
 * Module and Helper Functions
 ******************************************************************************/
function uc_sermepa_gateway_charge($order_id, $amount, $data) {
  global $user;

  $order = uc_order_load($order_id);

  $pan = $order->payment_details['cc_number'];
  $expiry = sprintf("%02d",round($order->payment_details['cc_exp_year']%100)).sprintf("%02d", $order->payment_details['cc_exp_month']);
  $cvv = $order->payment_details['cc_cvv'];

  $config = uc_sermepa_gateway_get_config();

  $response = _uc_sermepa_gateway_pay_order($config, $order_id, $order->order_total, $pan, $expiry, $cvv);

  if ($response){
    $order->data['tx_id']=$response;
    uc_order_save($order);
    
    $context = array(
      'revision' => 'formatted-original',
      'type' => 'amount',
    );
    $message = t('Credit card charged: !amount . Transaction: !tx_id', array('!amount' => uc_price($amount, $context), '!tx_id'=>$response));
    uc_order_comment_save($order_id, $user->uid, $message, 'admin');
    watchdog('uc_sermepa_gateway', t('Order !order_id accepted', array('!order_id' => intval($order_id)) ));

    uc_order_update_status($order->order_id, 'payment_received');
    
    $result = array(
    	'success' => TRUE,
      'comment' => $message,
      'message' => $message,
      'data' => array('module' => 'uc_sermepa_gateway', 'txn_id' => $response),
      'uid' => $user->uid,
    );
  }else {
    $message = t('Credit card charge failed.');
    uc_order_comment_save($order_id, $user->uid, $message, 'admin');
    watchdog('uc_sermepa_gateway', t('Order !order_id DENIED', array('!order_id' => intval($order_id))));

    $result = array(
    'success' => FALSE,
    'comment' => $message,
    'message' => $message,
    'uid' => $user->uid,
    // 'data' => $data,
    );
  }

  return $result;
}

/**
 * DS_MERCHANT_AMOUNT Obligatorio. Las dos últimas posiciones se consideran decimales, salvo en el caso de los Yenes que no tienen.
 * DS_MERCHANT_ORDER Obligatorio. Número de pedido único. Los 4 primeros dígitos deben ser numéricos.
 * DS_MERCHANT_MERCHANTCODE Obligatorio. Código FUC asignado al comercio.
 * DS_MERCHANT_TERMINAL Obligatorio. Número de Terminal.
 * DS_MERCHANT_CURRENCY Obligatorio. Moneda del comercio.
 * DS_MERCHANT_PAN Obligatorio. Tarjeta. Su longitud depende del tipo de tarjeta.
 * DS_MERCHANT_EXPIRYDATE Obligatorio. Caducidad de la tarjeta. Su formato es AAMM.
 * DS_MERCHANT_CVV2 Obligatorio. Código CVV2 de la tarjeta.
 * DS_MERCHANT_TRANSACTIONTYPE Obligatorio. Tipo de transacción. A – Pago tradicional, 1 – Preautorización, O – Autorización en diferido
 * DS_MERCHANT_MERCHANTSIGNATURE Obligatorio. Firma del comercio.
 */
function _uc_sermepa_gateway_pay_order($config, $order_id, $amount, $pan, $expiry_date, $cvv){
  $url = parse_url($config['uc_sermepa_gateway_ds_merchant_url']);

  //Ds_Merchant_Amount
  $ds_merchant_amount = round($amount*100);
  $data = '<DS_MERCHANT_AMOUNT>'.$ds_merchant_amount.'</DS_MERCHANT_AMOUNT>';
  //Ds_Merchant_Order
  $ds_merchant_order = date('ymdHis') + 100000000000;
  $data .= '<DS_MERCHANT_ORDER>'.$ds_merchant_order.'</DS_MERCHANT_ORDER>';
  //Ds_Merchant_Merchantcode
  $ds_merchant_merchantcode = $config['uc_sermepa_gateway_ds_merchant_code'];
  $data .= '<DS_MERCHANT_MERCHANTCODE>'.$ds_merchant_merchantcode.'</DS_MERCHANT_MERCHANTCODE>';
  //Ds_Merchant_Terminal
  $ds_merchant_terminal = $config['uc_sermepa_gateway_ds_merchant_terminal'];
  $data .= '<DS_MERCHANT_TERMINAL>'.$ds_merchant_terminal.'</DS_MERCHANT_TERMINAL>';
  //Ds_Merchant_Currency
  $ds_merchant_currency = $config['uc_sermepa_gateway_ds_merchant_currency'];
  $data .= '<DS_MERCHANT_CURRENCY>'.$ds_merchant_currency.'</DS_MERCHANT_CURRENCY>';
  //Ds_Merchant_PAN
  $ds_merchant_pan = $pan;
  $data .= '<DS_MERCHANT_PAN>'.$ds_merchant_pan.'</DS_MERCHANT_PAN>';
  //Ds_Merchant_ExpiryDate
  $ds_merchant_expirydate = $expiry_date;
  $data .= '<DS_MERCHANT_EXPIRYDATE>'.$ds_merchant_expirydate.'</DS_MERCHANT_EXPIRYDATE>';
  //Ds_Merchant_CVV2
  $ds_merchant_cvv = $cvv;
  $data .= '<DS_MERCHANT_CVV2>'.$ds_merchant_cvv.'</DS_MERCHANT_CVV2>';
  //Ds_Merchant_Transactiontype
  $ds_merchant_transactiontype = 'A'; // Traditional Payment
  $data .= '<DS_MERCHANT_TRANSACTIONTYPE>'.$ds_merchant_transactiontype.'</DS_MERCHANT_TRANSACTIONTYPE>';

  //Ds_Merchant_MerchatSignature
  $ds_merchant_signature = $config['uc_sermepa_gateway_ds_merchant_signature'];

  //Create message to sign
  $signed_message = _uc_sermepa_gateway_sign_message($config['uc_sermepa_gateway_encryption'], $ds_merchant_amount, $ds_merchant_order, $ds_merchant_merchantcode, $ds_merchant_currency, $ds_merchant_pan, $ds_merchant_cvv, $ds_merchant_transactiontype, $ds_merchant_signature);

  $data .= '<DS_MERCHANT_MERCHANTSIGNATURE>'.$signed_message.'</DS_MERCHANT_MERCHANTSIGNATURE>';

  $data = '<DATOSENTRADA>'.$data.'</DATOSENTRADA>';
  try {
    $clientOptions = array(
     'uri' => $url['scheme'].'://'.$url['host'].(!empty($url['port'])?':'.$url['port']:''),
     'location' => $config['uc_sermepa_gateway_ds_merchant_url'],
    );
    $client = new SoapClient(NULL, $clientOptions);
    $method = 'trataPeticion';
    $params = array($data);
    $response_xml = $client->__soapCall($method, $params);
    if(_uc_sermepa_gateway_parse_response($response_xml)){
      return $ds_merchant_order;
    }else{
      return FALSE;
    }
  }catch (Exception $e) {
    watchdog('uc_sermepa_gateway', $e->getMessage());
    return FALSE;
  }
}

function _uc_sermepa_gateway_sign_message($uc_sermepa_gateway_encryption, $ds_merchant_amount, $ds_merchant_order, $ds_merchant_merchantcode, $ds_merchant_currency, $ds_merchant_pan, $ds_merchant_cvv, $ds_merchant_transactiontype, $ds_merchant_signature){
  //DS_MERCHANT_AMOUNT + DS_MERCHANT_ORDER + DS_MERCHANT_MERCHANTCODE + DS_MERCHANT_CURRENCY + DS_MERCHANT_PAN + DS_MERCHANT_CVV2 + DS_MERCHANT_TRANSACTIONTYPE + CLAVE SECRETA
  $message = $ds_merchant_amount . $ds_merchant_order . $ds_merchant_merchantcode . $ds_merchant_currency . $ds_merchant_pan. $ds_merchant_cvv . $ds_merchant_transactiontype . $ds_merchant_signature;

  //Ds_Merchant_MerchantSignature
  if (strcmp($uc_sermepa_gateway_encryption, 'sha1-ampliado')===0) {
    $signed_message = sha1($message);
  }
  elseif(strcmp($uc_sermepa_gateway_encryption, 'sha1')===0) {
    module_load_include('inc', 'uc_sermepa_gateway', 'sha1');
    $sha = new SHA1;
    $digest1 = $sha->hash_string($message);
    $signed_message = $sha->hash_to_string($digest1);
  }

  return $signed_message;
}

/**
 * CODIGO Indica si la operación ha sido correcta.No indica si ha sido autorizada, solo si se ha procesado. 0 -> operación correcta.
 * Ds_Amount
 * Ds_Currency
 * Ds_Order
 * Ds_Signature
 * Ds_MerchantCode
 * Ds_Terminal
 * Ds_Response Indica el resultado de la operación. Autorizada o no.
 * Ds_AuthorisationCode Código de autorización en caso de existir para las operaciones autorizadas.
 * Ds_TransactionType A – Pago tradicional
 * 		1 – Preautorización
 * 		2 – Confirmación
 * 		3 – Devolución Automática
 * 		5 – Transacción Recurrente
 * 		6 – Transacción Sucesiva
 * 		9 – Anulación de Preautorización
 * 		O – Autorización en diferido
 * 		P - Confirmación de autorización en diferido
 * 		Q - Anulación de autorización en diferido
 * 		R – Autorización recurrente inicial diferido
 * 		S – Autorización recurrente sucesiva diferido
 * Ds_SecurePayment
 * 		0 – Seguro (no se aplica)
 * 		1 – No Seguro
 * Ds_Language
 */
function _uc_sermepa_gateway_parse_response($response_xml){
  $parsed_resp = simplexml_load_string($response_xml);

  if(property_exists($parsed_resp, 'CODIGO')){
    $code = (string) $parsed_resp->CODIGO;
    if($code==="0"){
      if(property_exists($parsed_resp, 'OPERACION')){
        $response = (string) $parsed_resp->OPERACION->Ds_Response;
        if($response==="0000"){
          return TRUE;
        }
      }
      return FALSE;
    }else{
      return FALSE;
    }
  }else{
    return FALSE;
  }
}

/**
 * Manage the settings of your Sermepa Gateway
 */
function uc_sermepa_gateway_admin_settings() {
  $form = array();
  $form['uc_sermepa_gateway_bankmode'] = array(
    '#type' => 'radios',
    '#title' => t('Mode of the bank'),
    '#default_value' => variable_get('uc_sermepa_gateway_bankmode', 'test'),
    '#options' => array('test' => t('Test'), 'live' => t('Live')),
    '#size' => 10,
    '#maxlength' => 5,
    '#required' => TRUE,
  );
  $form['uc_sermepa_gateway_encryption'] = array(
    '#type' => 'radios',
    '#title' => t('Method of encryption'),
    '#default_value' => variable_get('uc_sermepa_gateway_encryption', 'sha1'),
    '#options' => array(
      'sha1' => t('SHA'),
      'sha1-ampliado' => t('SHA Ampliado'),
  ),
    '#required' => TRUE,
  );
  $form['test'] = array(
  	'#type' => 'fieldset',
    '#collapsed' => TRUE,
    '#collapsible' => TRUE,
    '#title' => t('Sermepa Gateway Test mode configuration'),
  );
  $form['test']['uc_sermepa_gateway_ds_merchant_titular_test'] = array(
    '#type' => 'textfield',
    '#title' => t('Ds_Merchant_Titular'),
    '#default_value' => variable_get('uc_sermepa_gateway_ds_merchant_titular_test', 'Test Shop'),
    '#size' => 80,
    '#maxlength' => 255,
    '#required' => TRUE,
  );
  $form['test']['uc_sermepa_gateway_ds_merchant_code_test'] = array(
    '#type' => 'textfield',
    '#title' => t('Ds_MerchantCode'),
    '#default_value' => variable_get('uc_sermepa_gateway_ds_merchant_code_test', '999008881'),
    '#size' => 80,
    '#maxlength' => 255,
    '#required' => TRUE,
  );
  $form['test']['uc_sermepa_gateway_ds_merchant_signature_test'] = array(
    '#type' => 'textfield',
    '#title' => t('Ds_MerchantSignature'),
    '#default_value' => variable_get('uc_sermepa_gateway_ds_merchant_signature_test', 'qwertyasdf0123456789'),
    '#size' => 80,
    '#maxlength' => 255,
    '#required' => TRUE,
  );
  $form['test']['uc_sermepa_gateway_ds_merchant_terminal_test'] = array(
    '#type' => 'textfield',
    '#title' => t('Ds_Merchant_Terminal'),
    '#default_value' => variable_get('uc_sermepa_gateway_ds_merchant_terminal_test', '001'),
    '#size' => 5,
    '#maxlength' => 5,
    '#required' => TRUE,
  );
  $form['test']['uc_sermepa_gateway_ds_merchant_product_description_test'] = array(
    '#type' => 'textfield',
    '#title' => t('Ds_Merchant_ProductDescription'),
    '#default_value' => variable_get('uc_sermepa_gateway_ds_merchant_product_description_test', ''),
    '#size' => 80,
    '#maxlength' => 255,
  );
  $form['test']['uc_sermepa_gateway_ds_merchant_currency_test'] = array(
    '#type' => 'radios',
    '#title' => t('Currency'),
    '#default_value' => variable_get('uc_sermepa_gateway_ds_merchant_currency_test', '978'),
    '#options' => array(
      '978' => t('Euro'),
      '840' => t('Dollar'),
      '826' => t('Pound'),
  ),
    '#required' => TRUE,
  );
  $form['test']['uc_sermepa_gateway_ds_merchant_url_test'] = array(
    '#type' => 'textfield',
    '#title' => t('Web Service connect url'),
    '#default_value' => variable_get('uc_sermepa_gateway_ds_merchant_url_test', 'https://sis-i.sermepa.es:25443/sis/services/SerClsWSEntrada'),
    '#size' => 80,
    '#maxlength' => 255,
    '#required' => TRUE,
  );
  $form['live'] = array(
  	'#type' => 'fieldset',
    '#collapsed' => TRUE,
    '#collapsible' => TRUE,
    '#title' => t('Sermepa Gateway Live mode configuration'),
  );
  $form['live']['uc_sermepa_gateway_ds_merchant_titular'] = array(
    '#type' => 'textfield',
    '#title' => t('Ds_Merchant_Titular'),
    '#default_value' => variable_get('uc_sermepa_gateway_ds_merchant_titular', 'Live Shop'),
    '#size' => 80,
    '#maxlength' => 255,
    '#required' => TRUE,
  );
  $form['live']['uc_sermepa_gateway_ds_merchant_code'] = array(
    '#type' => 'textfield',
    '#title' => t('Ds_MerchantCode'),
    '#default_value' => variable_get('uc_sermepa_gateway_ds_merchant_code', '999008881'),
    '#size' => 80,
    '#maxlength' => 255,
    '#required' => TRUE,
  );
  $form['live']['uc_sermepa_gateway_ds_merchant_signature'] = array(
    '#type' => 'textfield',
    '#title' => t('Ds_MerchantSignature'),
    '#default_value' => variable_get('uc_sermepa_gateway_ds_merchant_signature', 'qwertyasdf0123456789'),
    '#size' => 80,
    '#maxlength' => 255,
    '#required' => TRUE,
  );
  $form['live']['uc_sermepa_gateway_ds_merchant_terminal'] = array(
    '#type' => 'textfield',
    '#title' => t('Ds_Merchant_Terminal'),
    '#default_value' => variable_get('uc_sermepa_gateway_ds_merchant_terminal', '001'),
    '#size' => 5,
    '#maxlength' => 5,
    '#required' => TRUE,
  );
  $form['live']['uc_sermepa_gateway_ds_merchant_product_description'] = array(
    '#type' => 'textfield',
    '#title' => t('Ds_Merchant_ProductDescription'),
    '#default_value' => variable_get('uc_sermepa_gateway_ds_merchant_product_description', ''),
    '#size' => 80,
    '#maxlength' => 255,
  );
  $form['live']['uc_sermepa_gateway_ds_merchant_currency'] = array(
    '#type' => 'radios',
    '#title' => t('Currency'),
    '#default_value' => variable_get('uc_sermepa_gateway_ds_merchant_currency', '978'),
    '#options' => array(
      '978' => t('Euro'),
      '840' => t('Dollar'),
      '826' => t('Pound'),
  ),
    '#required' => TRUE,
  );
  $form['live']['uc_sermepa_gateway_ds_merchant_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Web Service connect url'),
    '#default_value' => variable_get('uc_sermepa_gateway_ds_merchant_url', 'https://sis-i.sermepa.es/sis/services/SerClsWSEntrada'),
    '#size' => 80,
    '#maxlength' => 255,
    '#required' => TRUE,
  );

  return $form;
}

function uc_sermepa_gateway_get_config(){
  $config['uc_sermepa_gateway_bankmode'] = variable_get('uc_sermepa_gateway_bankmode', 'test');
  $config['uc_sermepa_gateway_encryption'] = variable_get('uc_sermepa_gateway_encryption', 'sha1');
  if(strcmp('test', $config['uc_sermepa_gateway_bankmode'])===0){
    $config['uc_sermepa_gateway_ds_merchant_titular'] = variable_get('uc_sermepa_gateway_ds_merchant_titular_test', 'Test Shop');
    $config['uc_sermepa_gateway_ds_merchant_code'] = variable_get('uc_sermepa_gateway_ds_merchant_code_test', '999008881');
    $config['uc_sermepa_gateway_ds_merchant_signature'] = variable_get('uc_sermepa_gateway_ds_merchant_signature_test', 'qwertyasdf0123456789');
    $config['uc_sermepa_gateway_ds_merchant_terminal'] = variable_get('uc_sermepa_gateway_ds_merchant_terminal_test', '001');
    $config['uc_sermepa_gateway_ds_merchant_product_description'] = variable_get('uc_sermepa_gateway_ds_merchant_product_description_test', '');
    $config['uc_sermepa_gateway_ds_merchant_currency'] = variable_get('uc_sermepa_gateway_ds_merchant_currency_test', '978');
    $config['uc_sermepa_gateway_ds_merchant_url'] = variable_get('uc_sermepa_gateway_ds_merchant_url_test', 'https://sis-i.sermepa.es:25443/sis/services/SerClsWSEntrada');
  }else{
    $config['uc_sermepa_gateway_ds_merchant_titular'] = variable_get('uc_sermepa_gateway_ds_merchant_titular', 'Live Shop');
    $config['uc_sermepa_gateway_ds_merchant_code'] = variable_get('uc_sermepa_gateway_ds_merchant_code', '999008881');
    $config['uc_sermepa_gateway_ds_merchant_signature'] = variable_get('uc_sermepa_gateway_ds_merchant_signature', 'qwertyasdf0123456789');
    $config['uc_sermepa_gateway_ds_merchant_terminal'] = variable_get('uc_sermepa_gateway_ds_merchant_terminal', '001');
    $config['uc_sermepa_gateway_ds_merchant_product_description'] = variable_get('uc_sermepa_gateway_ds_merchant_product_description', '');
    $config['uc_sermepa_gateway_ds_merchant_currency'] = variable_get('uc_sermepa_gateway_ds_merchant_currency', '978');
    $config['uc_sermepa_gateway_ds_merchant_url'] = variable_get('uc_sermepa_gateway_ds_merchant_url', 'https://sis.sermepa.es/sis/services/SerClsWSEntrada');
  }

  return $config;
}
